export const REGISTER_LABELS = {
  creatingFor: ' Profile Creating for',
  submit: 'SUBMIT',
  register: 'Register Now',
  groomName: 'Enter Bride/Groom name',
  motherTongue: 'Mother Tongue',
  religion: 'Religion',
  caste: 'Caste',
  countryLabel: 'Country',
  defaultCountry: 'India',
  stateLabel: 'State',
  districtLabel: 'District',
  cityLabel: 'City',
  villageLabel: 'Village',
  postalCodeLabel: 'Postal Code',
  phoneNumberLabel: 'Phone Number',
  maritalStatusLabel: 'Marital Status',
  emailLabel: 'Email',
  isAbroadLabel: 'Is Abroad',
  passwordLabel: 'Password',
  reEnterPasswordLabel: 'Re-Enter Password',
  termsAndConditionsNote: 'I Accept your Terms and Conditions',
  termsAndCondition: 'termsAndCondition',
  genderLabel: 'Gender',
  maleLabel: 'Male',
  femaleLabel: 'Female',
  dateOfBirth: 'Date of Birth',
  dateFormat: 'mm/dd/yyyy',
  day: 'Day',
  month: 'Month',
  year: 'Year',
  registerDescription: 'Join with us to find perfect match',
  registerNow: 'REGISTER NOW',
  Male: 'male',
  Female: 'female',
  vendorId: 'vendorId',
  adminId: 'adminId',
  superadminId: 'superadminId',
  image: 'image',
  firstNameLabel: 'First Name',
  lastNameLabel: 'Last Name',
  permanentAccNumber: 'Permanent Account Number (PAN)',
  aadharNumber: 'Aadhar Number',
  userName: 'User Name',
  packageName: 'Package Name',
  plan: 'Plan',
  remark: 'Remark',
  placeholder: 'This is  a placeholder',
  planInfo: 'Plan Information'
};
