const API = {
  getStateUrl: (countryId) => `States/${countryId}`,
  getDistrictsUrl: (stateId) => `Districts/${stateId}`,
  getCitiesUrl: (districtId) => `Cities/${districtId}`,
  getRegisterationDetails: `Register/GetRegisterDetails`,
  login: 'login',
  getCasteUrl: (religionId) => `Casts/${religionId}`,
  register: 'Register/PostRegister',
  validateEmail: 'Users/ValidateEmail',
  validateMobile: 'Users/ValidateMobile',
  forgotPassword: 'Login/ChangePassword',
  resetPassword: 'Login/ResetPassword',
  completeRegisterationApi: 'Register/CompleteRegistration',
  userRegisterationDetailsApi: (userId) => `Users/${userId}`,
  getPackagesDetail: 'Packages',
  deletePackagesDetail: 'Packages/DeletePackage',
  activatePackagesDetail: 'Packages/ActivatePackage',
  getDeactivateDetailsApi: 'Deactivate',
  deactivateApi: 'DeactivateDtl/PostDeactivateTypeDtl',
  updatePackages: 'Packages/UpdatePackage',
  sendOtp: 'Login/SendOTP',
  verifyOtp: 'Login/VerifyOTP',
  viewProfile: 'ViewProfile',
  searchResults: 'Search/SearchProfile',
  viewedProfiles: (userId) => `ViewProfile/${userId}`,
  getBalanceCount: (userId) => `Users/GetUserPackage/?userId=${userId}`,
  getVenBalanceCount: (userId) => `UserPackages/GetVendorPackage/${userId}`,
  userPhotosApi: (userId) => `UserPhotoes/GetUserPhoto?id=${userId}`,
  deleteUserPhotosApi: (imageId) => `UserPhotoes/DeleteUserPhoto?id=${imageId}`,
  uploadUserPhotosApi: `UserPhotoes/PostUserPhoto`,
  getVendorPackageApi: (payload) => `UserPackages/GetVendorPackage/?userId=${payload}`,
  editUserProfileApi: `Users/EditUserProfile`,
  userList: `Users/GetRoleWiseUserlist`,
  deActiveUser: `Users/DeActivateUser`,
  activeUser: `Users/ActivateUser`,
  vendorList: `Users/GetVendorlist`,
  executiveList: `Users/GetExecutiveList`,
  adminList: `Users/GetAdminList`,
  addVendorUserApi: `Vendor/VendorbyUserAdd`,
  changePassword: 'Register/ChangePassword',
  generatePaymentApi: 'Payments/PaymentComplete',
  sendNotificationApi: `Notifications/SendNotification`,
  getNotificationApi: (userId) => `Notifications/GetNotification?UserId=${userId}`,
  getRelatedUsersAPi: `Users/GetRelatedUsers`,
  userPaymentHistory: `GetRelatedPayments`,
  getTopVendor: `Vendor/GetTopVendors`,
  postalCOde: (code) => `pincode/IN/${code}`,
  generatePayments: `Payments/Generate`,
  contact: `contact-us`
};

export default API;
